analyzer:
  errors:
    prefer_const_constructors: ignore
    deprecated_member_use: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
